--- #YAML:1.0
name:               Mac-iPhoto-Shell
version:            0.16
abstract:           Play with iPhoto from the command line
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mac::Glue:  1.28
resources:
    repository:
        type:  git
        url:   https://github.com/CPAN-Adopt-Me/mac-iphoto-shell
        web:   https://github.com/CPAN-Adopt-Me/mac-iphoto-shell
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  2
